name: Build Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, release-4.13, release-4.13-compatibility]

jobs:
  build-test:
    name: resolve-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --prod --frozen-lockfile
      - run: yarn build
      - run: yarn build-mco
      - run: yarn install # Install dev. deps.
      - run: yarn lint
      - run: yarn format-test
      - run: yarn test-coverage
      - run: yarn analyze-odf
      - run: yarn analyze-mco
